# Generated by Django 5.0.7 on 2024-08-09 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_watchfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchfield',
            field=models.ManyToManyField(blank=True, related_name='listingWatchfield', to=settings.AUTH_USER_MODEL),
        ),
    ]
